
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fnplot.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 23;
  public static final int PLOT = 5;
  public static final int ELSE = 30;
  public static final int PLUS = 19;
  public static final int INT = 25;
  public static final int RBRACE = 13;
  public static final int RPAREN = 10;
  public static final int EQUAL = 15;
  public static final int SEMI = 11;
  public static final int IN = 4;
  public static final int CLEAR = 8;
  public static final int END = 31;
  public static final int IF = 28;
  public static final int COLON = 29;
  public static final int LPAREN = 9;
  public static final int LBRACKET = 16;
  public static final int LBRACE = 12;
  public static final int RBRACKET = 17;
  public static final int TABULATE = 6;
  public static final int COMMA = 14;
  public static final int CMP = 32;
  public static final int EOF = 0;
  public static final int DIV = 22;
  public static final int DOTDOT = 18;
  public static final int MINUS = 20;
  public static final int error = 1;
  public static final int LET = 3;
  public static final int ASSIGN = 24;
  public static final int FOR = 7;
  public static final int REAL = 26;
  public static final int MUL = 21;
  public static final int VAR = 27;
  public static final int FUN = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUN",
  "LET",
  "IN",
  "PLOT",
  "TABULATE",
  "FOR",
  "CLEAR",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "EQUAL",
  "LBRACKET",
  "RBRACKET",
  "DOTDOT",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "ASSIGN",
  "INT",
  "REAL",
  "VAR",
  "IF",
  "COLON",
  "ELSE",
  "END",
  "CMP"
  };
}

